name: "CI"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: restore current cache
      id: cache-restore
      uses: actions/cache/restore@v3
      with:
        path: nix-store.nar
        key: nix-store-nar-${{ hashFiles('flake.lock') }}
    - if: steps.cache-restore.outputs.cache-hit == 'true'
      run: |
        nix-store --import < nix-store.nar
        rm nix-store.nar

    - run: nix develop

    - name: dump store
      run: nix-store --export > nix-store.nar
    - name: save current cache
      uses: actions/cache/save@v3
      id: cache
      with:
        path: nix-store.nar
        key: nix-store-nar-${{ hashFiles('flake.lock') }}


    - run: nix build

