name: "CI"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: restore current cache
      uses: divnix/nix-cache-action/restore@v3
      with:
        path: /nix/store
        key: nix-store-${{ hashFiles('flake.lock') }}
    - run: nix develop
    - run: nix build

    - name: save current cache
      uses: divnix/nix-cache-action/save@v3
      id: cache
      with:
        path: /nix/store
        key: nix-store-${{ hashFiles('flake.lock') }}
